### ISSUE TITLE
Hookers

### ISSUE THREAD

**Issue by Swampy821** [Swampy821/PublIRC#2]
Make some hookers

**Comment by SkySom** [comment]
BETTER BE BLACKJACK WITH THESE HOOKERS

**Comment by Swampy821** [comment]
I'M NOT MAKING THE BLACKJACK! FUCK YOU!

**Comment by SkySom** [comment]
THAT'S BECAUSE YOU LACK THE SKILLS TOO. THANK GOD CORE CAN
